language: go
go:
- 1.3
services:
- memcached
install:
- make
script:
- make test
- PUSHGO_TEST_STORAGE_MC_HOSTS=localhost:11211 make test-memcached
before_deploy:
- sudo apt-get -qq remove -y libmemcached-dev
- sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ utopic main"
- sudo apt-get -qq update
- sudo apt-get install -y libmemcached-dev
- make simplepush
- mkdir -p build/server
- gzip simplepush
- cp simplepush.gz build/server/simplepush-linux-$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT.gz
deploy:
  provider: s3
  access_key_id: AKIAJPJ3YT7MAF55UGDA
  secret_access_key:
    secure: Iyc3eLG0H/pFot1eNdsgulF0A8SB2ih4gc+FjhxQNE/cOX5Vy7r0ARNkUHLkqi/HkUkP2Dz27OqTmhpcRQ/71rQp/k9IXJaB3EF3VNDnNo7vw6S+wIXG19a0KQC9YGsjDWvCefFkKvOlkviHU/eS7p09Q2dRMNUNL5jUKd/SoKM=
  bucket: travis-binary-uploading
  skip_cleanup: true
  local-dir: build/server
  upload-dir: simplepush-server
  on:
    branch: dev
